#app
server:
  port: 9012

file:
  upload:
    path: ${user.home}/containers/${spring.application.name}/data/files

#spring
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 修改单次文件上传文件大小不能超过100MB
      max-request-size: 500MB # 设置单次文件请求总大小不能超过500MB

  jmx:
    default-domain: lens_blog_picture
  thymeleaf:
    cache: true   #关闭缓存
  application:
    name: lens-blog-picture
  security:
    user:
      name: lens
      password: lens
  boot:
    admin:
      client:
        enabled: true
        url: http://${lens-blog-monitor:localhost}:9020
        username: lens
        password: lens
        instance:
          service-base-url: http://${lens-blog-picture:localhost}:9012

  #redis
  redis:
    host: ${lens-redis:localhost} #redis的主机ip
    port: 6379
    #password: mogu2018  # 客户端没有设置密码，服务器中redis默认密码为 mogu2018

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${lens-zipkin:localhost}:9411  # 指定了Zipkin服务器的地址

  # DATABASE CONFIG
  datasource:
    username: lens
    password: lens
    url: jdbc:mysql://${lens-mariadb:localhost}:33306/lens_blog_picture?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    static-path-pattern: /upload/**
  resources:
    static-locations: classpath:/static/upload

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lens.blog.picture.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false