spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8850/rsa/publicKey'
  redis:
    database: 0
    host: ${lens-redis:localhost}
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        lowerCaseServiceId: true
      routes:
        - id: gzh
          uri: lb://gzh
          predicates:
            - Path=/api/v1/wx/gzh/**
          filters:
            - StripPrefix=4
        - id: lens-auth
          uri: lb://lens-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
        - id: lens-blog-admin-backend
          uri: lb://lens-blog-admin-backend
          predicates:
            - Path=/api/v1/blog/admin/**
          filters:
            - StripPrefix=4
        - id: lens-blog-backend
          uri: lb://lens-blog-backend
          predicates:
            - Path=/api/v1/blog/web/**
          filters:
            - StripPrefix=4
        - id: lens-blog-picture
          uri: lb://lens-blog-picture
          predicates:
            - Path=/api/v1/blog/picture/**
          filters:
            - StripPrefix=4
        - id: lens-blog-search
          uri: lb://lens-blog-search
          predicates:
            - Path=/api/v1/blog/search/**
          filters:
            - StripPrefix=4
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/api/v1/auth/oauth/token"

# 日志配置
logging:
  level:
    com.lens: debug
    org.springframework: debug