server:
  port: 9010

spring:
  profiles:
    active: dev



---

spring:
  application:
    name: platform
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        metadata:
          VERSION: 1.0
      config:
        server-addr: nacos:8848
        file-extension: yml
  profiles: prod

---

spring:
  application:
    name: platform
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          VERSION: 1.0
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  profiles: dev