server:
  port: 8888
  
spring:
  datasource:
    username: root
  
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create  
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect