#app
server:
  port: 9011

#阿里大于
accessKeyId: XXXXXXXXXXXXXXXXXXXXX #修改成自己的
accessKeySecret: XXXXXXXXXXXXXXXXXXXXXXX #修改成自己的

#spring
spring:
  jmx:
    default-domain: lens_blog_sms
  thymeleaf:
    cache: true   #关闭缓存
  application:
    name: lens-blog-sms
  security:
    user:
      name: lens
      password: lens
  #redis
  redis:
    host: ${lens-redis:localhost} #redis的主机ip
    port: 6379

  #RabbitMq
  rabbitmq:
    host: ${lens-rabbitmq:localhost} #rabbitmq的主机ip
    port: 5672
    username: lens
    password: lens
  #mail
  mail:
    username: lensson_chen@sina.com
    password: lensson1 #授权码开启SMTP服务里设置
    host: smtp.sina.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false
  boot:
    admin:
      client:
        enabled: true
        url: http://${lens-blog-monitor:localhost}:9020
        username: lens
        password: lens
        instance:
          service-base-url: http://${lens-blog-sms:localhost}:9011

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${lens-zipkin:localhost}:9411  # 指定了Zipkin服务器的地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always