server:
  port: 9013
spring:
  application:
    name: lens-blog-search
  jmx:
    default-domain: lens_blog_search
  security:
    user:
      name: lens
      password: lens
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${lens-elasticsearch:localhost}:9200
    solr:
      host: http://${lens-solr:localhost}:8983/solr
      core: collection1
      repositories:
      enabled: true

  #redis
  redis:
    host: ${lens-redis:localhost} #redis的主机ip
    port: 6379

  rabbitmq:
    host: ${lens-rabbitmq:localhost} #rabbitmq的主机ip
    port: 5672
    username: lens
    password: lens

  boot:
    admin:
      client:
        enabled: true
        url: http://${lens-blog-monitor:localhost}:9020
        username: lens
        password: lens
        instance:
          service-base-url: http://${lens-blog-search:localhost}:9013

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${lens-zipkin:localhost}:9411  # 指定了Zipkin服务器的地址



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always