spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: 172.17.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 日志配置
logging:
  level:
    com.lens: debug
    org.springframework: info