name: Build lens-solution All Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build-environment: github
    #========================== lens-blog =================================
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17.0.9
      - uses: actions/setup-node@v1
        with:
          node-version: 8.17.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Build All lens-solution Modules
        run: |
          echo '=====开始mvn clean====='
          mvn clean
          echo '=====开始mvn install&&package====='
          mvn install -DskipTests=true && mvn package -DskipTests=true


      - name: Build lens-blog Docker Images
        run: |
          cd lens-blog
          echo '=====开始构建lens-blog镜像群====='
          echo '=====开始构建lens-blog-admin-backend====='
          cd lens-blog-admin-backend
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-monitor====='
          cd lens-blog-monitor
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-picture====='
          cd lens-blog-picture
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-search====='
          cd lens-blog-search
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-sms====='
          cd lens-blog-sms
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-spider====='
          cd lens-blog-spider
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-backend====='
          cd lens-blog-backend
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-admin-vue-frontend====='
          cd lens-blog-admin-vue-frontend
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-blog-vue-frontend====='
          cd lens-blog-vue-frontend
          mvn dockerfile:build
          cd ..
          echo '=====完成构建lens-blog镜像群====='
      - name: Build lens-wx Docker Images
        run: |
          echo '=====开始构建lens-wx镜像群====='
          echo '=====开始构建lens-gzh-backend====='
          cd lens-wx
          cd lens-gzh-frontend
          mvn dockerfile:build
          cd ..
          echo '=====开始构建lens-gzh-frontend====='
          cd lens-gzh-frontend
          docker build . -t lensson/lens-gzh-frontend:latest
          cd ..
          echo '=====完成构建lens-wx镜像群====='
      # 登录到 dockerhub
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push lens-blog Docker Image
        run: |
          echo '=====开始上传lens-blog镜像====='
          echo '=====开始上传lens-blog-admin-backend====='
          docker push lensson/lens-blog-admin-backend:latest
          echo '=====开始上传lens-blog-monitor====='
          docker push lensson/lens-blog-monitor:latest
          echo '=====开始上传lens-blog-picture====='
          docker push lensson/lens-blog-picture:latest
          echo '=====开始上传lens-blog-search====='
          docker push lensson/lens-blog-search:latest
          echo '=====开始上传lens-blog-sms====='
          docker push lensson/lens-blog-sms:latest
          echo '=====开始上传lens-blog-spider====='
          docker push lensson/lens-blog-spider:latest
          echo '=====开始上传lens-blog-backend====='
          docker push lensson/lens-blog-backend:latest
          echo '=====开始上传lens-blog-admin-vue-frontend====='
          docker push lensson/lens-blog-admin-vue-frontend:latest
          echo '=====开始上传lens-blog-vue-frontend====='
          docker push lensson/lens-blog-vue-frontend:latest
          echo '=====镜像上传结束====='
      - name: Push lens-wx Docker Image
        run: |
          echo '=====开始上传lens-wx镜像====='
          echo '=====开始上传lens-gzh-backend====='
          docker push lensson/lens-gzh-backend:latest
          echo '=====开始上传lens-gzh-frontend====='
          docker push lensson/lens-gzh-frontend:latest
          echo '=====镜像上传结束====='