name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8    
#      - name: Build the lens-blog-backend Docker image
      - name: Maven Clean Install
        run: |
          cd lens-blog
          echo '=====开始mvn clean====='
          mvn clean
          echo '=====开始mvn install&&package====='
          mvn install -DskipTests=true && mvn package -DskipTests=true
          
