name: Build lens-solution All Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

#========================== lens-blog =================================
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8    
      - name: Maven Clean Install All lens-blog Backend Modules
        run: |
          cd lens-blog
          echo '=====开始mvn clean====='
          mvn clean
          echo '=====开始mvn install&&package====='
          mvn install -DskipTests=true && mvn package -DskipTests=true
          
      - name: Build lens-blog-vue-admin-frontend and lens-blog-vue-frontend
        run: |
          echo '=====开始安装lens-blog-vue-admin-frontend依赖====='
          cd ./lens-blog-vue-admin-frontend
          npm install
          npm run build
          cd ..
          echo '=====开始安装lens-blog-vue-frontend依赖====='
          cd ./lens-blog-vue-frontend
          npm install
          npm run build
          cd ..
          
      - name: Build lens-blog Java Docker Images
        run: |
          echo '=====开始构建镜像====='
          echo '=====开始构建lens-blog-admin-backend====='
          cd lens-blog-admin-backend
          mvn dockerfile:build
          cd ..
          
          echo '=====开始构建mogu_monitor====='
          cd lens-blog-monitor
          mvn dockerfile:build
          cd ..          
